# 넘파이

넘파이 : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패ㅣ지

array() 함수: 리스트와 같은 인자를 입력 받아 ndarray로 변환하는 기능

shape 변수: ndarray의 크기, 배열의 차원 알려줌

ndarray.shape : 차원과 크기를 튜플 형태로 나타냄



In [1]:
import numpy as np

In [ ]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
#이거는 1개의 row, 3개의 column을 가진 2차원 데이터
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원,array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원,array3:  2차원


array() 함수의 인자로는 리스트 객체 사용
[]는 1차원, [[]]는 2차원

**ndarray의 데이터 타임**

숫자형: int, unsigned int, float, complex 타입

ndarray내의 데이터 타입은 같은 데이터 타입만 가능하다

dtype : ndarray  내의 데이터 타입 확인

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


list2처럼 문자와 int형이 섞여있을 때 ndarray로 변환하면 array2의 숫자형 값은 모두 문자열로 변환된다.

int형과 float형이 섞여있으면 int형이 float형으로 변환된다.

-> 서로 다른 데이터 타입이 섞여있으면 데이터 타입이 더 큰 데이터 타입으로 변환된다

astype(): ndarray 내 데이터값의 타입 변경, 인자로 원하는 타입 써서 지정 (메모리 절약해야할 때 이용)

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

arange() : array를 range()로 표현하는 것, 0부터 인자 값-1 까지의 값을 순차적으로 ndarray 데이터 값으로 변환

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros() : 함수인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환

ones() : 함수인자로 shape를 입력하면 모든 값을 1로 채운 shape의 ndarray를 반환

dtype을 지정하지 않으면 default로 float64형의 데이터로 ndarray 채움


In [ ]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#ndarray의 차원과 크기를 변경하는 reshape()

reshape(): ndarray를 특정 차원 및 크기로 변환

In [ ]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)



array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3)
#오류

ValueError: ignored

reshape() 함수에서 인자로 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다.


In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)
#오류

ValueError: ignored

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5.shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#인덱싱(indexing)

1. 특정 데이터만 추출 : 원하는 인덱스 값 지정
2. 슬라이싱 : 연속된 인덱스로 추출, : 기호 이용하면 시작 인덱스부터 종료인덱스-1까지 반환
3. 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트로 지정해서 그 위치의 데이터 반환
4. 불린 인덱싱 : 특정 조건에 해당하는지 여부인 true/false 값 인덱싱 집합을 기반으로 true에 해당하는 인덱스 위치에 있는 데이터 반환

<단일 값 추출>

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


index는 0부터 시작한다.
- -기호를 사용하면 맨 뒤에서부터 데이터 추출할 수 있다.

In [ ]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [ ]:
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
#1차원 ndarray를 2차원의 3x3 ndarray로 변환 후 [row,col]fh 2차원 ndarray에서 데이터 추출

array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가르키는 값:', array2d[0,0])
print('(row=0,col=1) index 가르키는 값:', array2d[0,1])
print('(row=1,col=0) index 가르키는 값:', array2d[1,0])
print('(row=2,col=2) index 가르키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가르키는 값: 1
(row=0,col=1) index 가르키는 값: 2
(row=1,col=0) index 가르키는 값: 4
(row=2,col=2) index 가르키는 값: 9


- axis 0: row 방향의 축
- axis 1: column 방향의 축
축 기반의 연산에서 axis가 생략되면 axis 0 의미

**슬라이싱**

- ':' 기호를 이용하여 슬라이싱 추출
- 시작인덱스에서 종료인덱스 -1 위치의 데이터의 ndarray 반환

In [ ]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- ':' 기호 앞에 시작 인덱스를 생략하면 맨처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원에서는 ,로 row column 을 지칭하여 slicing 한다
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2[1] shape: (3,)


**팬시 인덱싱**

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방법

True 값에 있는 위치 인덱스 값으로 자동 반환

In [ ]:
array1d=np.arange(start=1,stop=10)
# [ ]안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


1. array1d>5 와 같이 ndarray 의 필터링 조건을 [ ]안에 기재
2. False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(True 값을 가진 인덱스를 저장)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

**행렬의 정렬 - sort() argsort()**

- 행렬 정렬
np.sort(), ndarray.sort(), argsort()

In [3]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()러 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


- np.sort() : 원본 행렬을 변경하지 않고 정렬된 형태로 반환
- ndarray.sort() : 원본 행렬 자체를 정렬한 값으로 변환

-[::-1] : 내림차순으로 정렬하기 위한 방법

-np.sort()[::-1]와 동일

In [4]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [9]:
#행렬이 2차원 이상일때
array2d=np.array([[8,12],
                  [7,1 ]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스 반환하기

np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스

In [10]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [11]:
#내림차순
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [12]:
import numpy as np
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

- 행렬 내적(행렬 곱)

  np.dot() 이용하여 계산

In [17]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
           [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)


행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬
  전치행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬

    transpose() 이용

In [18]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
